---
- name: Remove Apache from ubuntuservers
  hosts: ubuntuservers
  tasks:
   - name: Uninstalling Apache
     ansible.builtin.apt:
       name: apache2
       state: absent
       update_cache: true   # apt update ile ayni
       autoremove: true     # otomatik siliyor
       purge: true          # TÃ¼m kalintilari kaldirir

- name: Remove Apache and wget from webservers
  hosts: webservers
  tasks:
   - name: removing apache and wget
     ansible.builtin.yum:
       pkg: "{{ item }}"
       state: absent
     loop:
       - httpd
       - wget
